/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CustomButton: typeof import('./components/common/CustomButton.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    QuizQuestionCard: typeof import('./components/quiz/QuizQuestionCard.vue')['default']
    QuizResultsCard: typeof import('./components/quiz/QuizResultsCard.vue')['default']
    QuizStartCard: typeof import('./components/quiz/QuizStartCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
